microsoft/monaco-editor

website/index/samples/sample.c.txt
This code comes from the compiler-tests repo: https://github.com/Microsoft/compiler-tests/blob/master/seh/xcpt4u.c
If there's a problem with that source for some reason, the Windows-driver-samples repo also has some C code: https://github.com/Microsoft/Windows-driver-samples/blob/master/network/modem/fakemodem/ioctl.c
Other Microsoft owned repos with C code: https://github.com/search?utf8=%E2%9C%93&q=language%3Ac+user%3Amicrosoft&type=Repositories&ref=searchresults
Fixes #11
=> Updated C code sample

test/samples-all.generated.js, test/samples/sample.yaml.txt, website/index/samples/sample.yaml.txt
Follow up from https://github.com/Microsoft/monaco-languages/pull/12.
I am not sure, if it is correct to include the generated file. I have updated and included it because it existed before.
=> Add YAML samples

test/playground.generated/creating-the-editor-editor-basic-options.html, website/playground/new-samples/creating-the-editor/editor-basic-options/sample.js
This PR fixes the samples that are using the deprecated API of lineNumbers (boolean). They now use `"on"`, `"off"` and `"relative"`.
=> Fix line number API usage

website/index.html
- Logo added in footer to link Microsoft official website ('https://www.microsoft.com/')
=> adding microsoft logo to footer

README.md
=> add LSP support

website/index/samples/sample.clojure.txt
=> added clojure exampple

package-lock.json
Npm reports 7 vurnerabilities in the npm packages. This fixes atleast 2/7 of them, the others will require another audit.
=> fix 2 of 7 npm package vurnerabilities

CONTRIBUTING.md
* removed the repetition of "being able to build"
=> style: Updated CONTRIBUTING.md

website/monarch.html
=> Removing obsolete Note in Monarch Docs

README.md
It kind of sticks out, being in the very first sentence.
https://en.wikipedia.org/wiki/Comma_splice
=> Correct comma splice in README.md

website/monarch/monarch.js
Commented code should be avoided. There are more downsides then upsides on keeping it. If this piece of code is needed in the future, `git diff` is a better option.
=> Remove commented code

README.md
changed the license block, to make it similar to other microsoft repositories
=> changed the license block of readme

CHANGELOG.md, docs/integrate-esm.md, website/monarch.html
Fixed the few typos and grammar mistakes, which I noticed.
=> Fixed typos in website page and CHANGELOG

test/samples/sample.csharp.txt
Now prints prime numbers from 1 to 100.
=> Updated C# sample code for a simpler game.

website/playground/new-samples/extending-language-services/completion-provider-example/sample.js
=> fix demo: completion provider example

website/playground/new-samples/extending-language-services/symbols-provider-example/sample.js
add mandatory fields, plus a quick guide to the user on how to see the symbols list
closes #1602
=> playground: update symbols-provider-example

CONTRIBUTING.md
contributing: extra details in "running website locally" section
another step is required to start the local webserver
=> contributing: add details for running website locally

gulpfile.js, test/playground.generated/extending-language-services-configure-javascript-defaults.html, website/playground/new-samples/extending-language-services/configure-javascript-defaults/sample.js
This is basically implementation of feature added in https://github.com/microsoft/vscode/pull/85129
=> Update example: allow peek definition

website/playground/new-samples/extending-language-services/semantic-tokens-provider-example/sample.js
=> semantic-tokens-provider-example/sample.js code format

docs/integrate-esm.md
=> Add usage with Vite to ESM Integrate doc

website/playground/new-samples/customizing-the-appearence/tokens-and-colors/sample.js, website/playground/new-samples/extending-language-services/custom-languages/sample.js
=> Fix some errors on the website playground

webpack-plugin/package-lock.json, webpack-plugin/package.json, webpack-plugin/src/loader-utils.d.ts, webpack-plugin/src/loaders/include.ts
=> fix(monaco-editor-webpack-plugin): load monaco-editor with webpack 4

samples/browser-esm-parcel/index.html, samples/browser-esm-parcel/package.json, samples/browser-esm-parcel/src/index.js
A PR as per: https://github.com/microsoft/monaco-editor/issues/2823#issuecomment-993706028
=> doc: (samples) Simplify Browser ESM Parcel build

.github/workflows/ci.yml, build/fs.ts, build/importTypescript.ts, package.json, test/smoke/esbuild/esbuild.html, test/smoke/esbuild/index.js, test/smoke/package-esbuild.ts, test/smoke/runner.js, test/smoke/smoke.test.js
ref https://github.com/microsoft/monaco-editor/issues/2941
=> Add smoke test for packaging using esbuild 

CONTRIBUTING.md
I ran into this when creating #3096
=> Document samples are needed when adding a language

src/basic-languages/kotlin/kotlin.contribution.ts
This closes #3454 by adding .kts as an extension.
=> Add .kts as a file extension

src/basic-languages/typescript/typescript.ts
https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/#hamilton
=> add `satisfies` keyword to typescript

src/basic-languages/cpp/cpp.ts
=> Recognize \0 as an escape sequence

.github/workflows/info-needed-closer.yml
With the label change this no longer worked, updates it to use the latest label
=> Update info needed closer

.devcontainer/devcontainer.json
Fixes https://github.com/microsoft/monaco-editor/issues/3523
FYI @chrmarti
=> Adds devcontainer.json

website/src/website/pages/DocsPage.tsx
=> Fixes #3563

website/src/website/data/playground-samples/creating-the-editor/web-component/sample.html, website/src/website/data/playground-samples/creating-the-editor/web-component/sample.js, website/src/website/data/playground-samples/creating-the-editor/web-component/sample.json
=> Fixes #3588

package-lock.json, package.json
=> Fixes #3601

package.json
To fix https://github.com/microsoft/monaco-editor/issues/3601
=> Sets version to 0.36.1

src/language/typescript/languageFeatures.ts, src/language/typescript/monaco.contribution.ts, src/language/typescript/tsWorker.ts
=> Fixes #3565

website/src/website/pages/playground/Preview.tsx
fix example iframe don't alert
fix https://github.com/microsoft/monaco-editor/issues/3767
=> fix example iframe don't alert

website/src/website/data/playground-samples/interacting-with-the-editor/line-and-inline-decorations/sample.js, website/src/website/data/playground-samples/interacting-with-the-editor/listening-to-mouse-events/sample.js, website/src/website/data/playground-samples/interacting-with-the-editor/rendering-glyphs-in-the-margin/sample.js
new version  `deltaDecorations` is Deprecated
so  use `createDecorationsCollection` replace `deltaDecorations`
=> use createDecorationsCollection replace deltaDecorations

website/package.json, website/yarn.lock
Fixes #3853 by downgrading typescript.
Compare https://www.typescriptlang.org/play?target=99&module=1&ts=4.7.4#code/KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjThmCRgAo0EBbYALjkqkLQHMBKOAbwFgAUHBFwMJSnCgVcAG3gBeOFSGi1iAO4JC8QnUiwqAAwB0JgPRnzAEwQwE5gBYQGAWiT0wsiuY-7vJgAkvLQMAL4mMCAwRlyqolwm1sDYCHIwANxCYUA
with https://www.typescriptlang.org/play?target=99&module=1&ts=5.0.2#code/KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjThmCRgAo0EBbYALjkqkLQHMBKOAbwFgAUHBFwMJSnCgVcAG3gBeOFSGi1iAO4JC8QnUiwqAAwB0JgPRnzAEwQwE5gBYQGAWiT0wsiuY-7vJgAkvLQMAL4mMCAwRlyqolwm1sDYCHIwANxCYUA
=> Fixes #3853

src/basic-languages/yaml/yaml.test.ts, src/basic-languages/yaml/yaml.ts
This is a naïve attempt to fix odd cases of the YAML highlighting I have experienced.
=> Various YAML improvements

package-lock.json, package.json, src/basic-languages/_.contribution.ts
=> Fixes #3534

src/basic-languages/monaco.contribution.ts, src/basic-languages/wgsl/wgsl.contribution.ts, src/basic-languages/wgsl/wgsl.test.ts, src/basic-languages/wgsl/wgsl.ts, website/src/website/data/home-samples/sample.wgsl.txt
=> Add WebGPU Shading Language tokenizer, with tests

build/importTypescript.ts, test/manual/dev-setup.js, website/src/monaco-loader.ts, website/src/runner/index.ts, website/static/monarch/monarch.js
Adresses https://github.com/microsoft/vscode-internalbacklog/issues/4449
=> Adds CodeQL exceptions

src/basic-languages/twig/twig.test.ts, src/basic-languages/twig/twig.ts
=> Fix Twig's plain text class expression

website/src/website/data/playground-samples/extending-language-services/color-provider-example/sample.js
In relation to https://github.com/microsoft/monaco-editor/issues/4284#issuecomment-1856168603
=> Changing the color ranges of the color provider example in the playground

MAINTAINING.md
=> Adding some detail in MAINTAINING.md for trigger build step

.github/workflows/ci.yml, website/src/website/pages/playground/PlaygroundPageContent.tsx
fixes https://github.com/microsoft/monaco-editor/issues/4898
=> Fixes https://github.com/microsoft/monaco-editor/issues/4799

src/basic-languages/sql/keywords.js
- Snowflake SQL keywords were not included here
- Added Snowflake SQL keywords from this Snowflake doc: https://docs.snowflake.com/en/sql-reference/reserved-keywords
=> Add snowflake sql keywords

build/build-monaco-editor.ts
Fixes https://github.com/microsoft/monaco-editor/issues/4981
=> Fixes https://github.com/microsoft/monaco-editor/issues/4981
