microsoft/monaco-editor

- package.json
npm scripts will use the executables in `node_modules/.bin` by default: https://docs.npmjs.com/misc/scripts
> Remove unnecessary paths to executables in npm scripts

- website/index/index.css
Button can be found in filter row.
This fixes issue #6 Website dropdown is off by 1 or 2
> Fixed spacing beetwen button and dropdown menu

- website/monarch/monarch.css
Not every OS has `Consolas` as an installed font, for those browsers, default to `monospace`.
Previously:
> style(monarch.css): Add monospace default for code

- test/playground.generated/extending-language-services-custom-languages.html
- website/playground/new-samples/extending-language-services/custom-languages/sample.js
Since the 0.9.0 release, the monaco-editor no longer supports the build-in snippet syntax. 
This PR updates the playground samples to use SnippetString and updates the syntax of the snippets to use the TextMate syntax described here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax
> Update custom-languages playground sample to use SnippetString

- test/playground.generated/extending-language-services-configure-json-defaults.html
- website/playground/new-samples/extending-language-services/configure-json-defaults/sample.js
The [Configure JSON defaults sample](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults) in the playground is currently broken. Validation errors never show up even when the JSON doesn't conform to the schema.
Here's what I had to change to get it to work:
* Set `validate` to `true` in diagnostic options.
* Create a model; for each schema, set `fileMatch` to a value that matches the `uri` used when creating the model. Reference: https://github.com/Microsoft/monaco-editor/issues/191#issuecomment-248034168
I also changed the initial JSON so that the validation errors show up without editing the JSON.
Ran `gulp simpleserver`. The validation errors now show up as expected.
> Fix `Configure JSON defaults` sample

- website/playground/new-samples/extending-language-services/completion-provider-example/sample.js
This just adds a line break in an playground example that makes the code more readable (in my opinion).
> Add linebreak for if

- CHANGELOG.md
I've added links to the CHANGELOG.md file to make it easier for readers to see what went in a new release. Tags don't exist for `0.7.1` and `0.7.0` so I didn't create any links in that area.
> Add tag comparison links to CHANGELOG.md

- gulpfile.js
- package-lock.json
- package.json
- webpack/features.js
- webpack/index.js
- webpack/languages.js
- webpack/loaders/include.js
- webpack/plugins/AddWorkerEntryPointPlugin.js
The recent ESM build works brilliantly, and it's really exciting to finally have the monaco editor as a first-class citizen of the webpack ecosystem.
Unfortunately, the user needs to make several non-intuitive additions to their webpack config and source code before they can use it:
1. Add additional `entry` points for each of the required worker scrips
2. Manually create a `MonacoEnvironment` that references the output paths provided for these entry points
3. Add a `webpack.IgnorePlugin()` that references an internal file within `monaco-editor` package
4. (optional) Manually `import` specific feature modules from deep within the `monaco-editor` package if the user wants to customise the editor build
None of these steps is obvious without deep knowledge of how `monaco-editor` code is …
> Add webpack loader plugin to simplify ESM usage

- test/playground.generated/extending-language-services-folding-provider-example.html
- test/playground.generated/index.html
- website/playground/new-samples/all.js
- website/playground/new-samples/extending-language-services/folding-provider-example/sample.html
- website/playground/new-samples/extending-language-services/folding-provider-example/sample.js
A new `monaco.languages.registerFoldingRangeProvider` API was added in 0.13.0 to allow people to create custom folding regions. I've created a small example that demonstrates how to use this API for the Monaco Playground.
> Add folding provider sample to the playground

- website/monarch.html
The xdot comment using hash does only include one following character. It should be like `//`, spanning to the end of the line.
> Fix hash comment in xdot sample

- test/playground.generated/interacting-with-the-editor-listening-to-mouse-events.html
- website/playground/new-samples/interacting-with-the-editor/listening-to-mouse-events/sample.js
The `nativeContextMenu` property did not work, so I changed it to the` contextmenu` property.
> Fix playground sample option

- docs/integrate-amd-cross.md
A small mistake fixed. `baseUrl` should be the same as in the option 2 (read below in the same document) . If not it won't work and can give unnecessary pain to newcomers. Good work :) keep it up!
> fix small error in integration docs

- CHANGELOG.md
Note that two of the links don't work because the `v0.14.0` tag actually doesn't exist in the repository. :(
> Add missing links in CHANGELOG.md

- README.md
update grammar and include links where appropriate
> correct README grammar

- .github/issue_template.md
- ISSUE_TEMPLATE
Move the ISSUE_TEMPLATE out of the root folder and into an hidden .github folder to have the same behavior on most of the microsoft repos.
Also added bold stylings to the required fields for creating an issue.
// https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/#adding-an-issue-template
> Move issue template to '.github' folder and add some styling for better readability

- CONTRIBUTING.md
Link to vscode prerequisites now go directly to the Prerequisites Header of the vscode Contributing doc.
addresses issue #1154
> Fixed prerequisites link in Contributing.md

- test/samples/sample.java.txt
I thought that the JUnit sample was, frankly, a lousy example of Java code. So I wrote a full FizzBuzz program to use as a new example. My program uses most of the common Java syntax and logic flows (block comment styles, if/else/for statement styles and patterns, etc) to hopefully provide a better Java sample.
> Added better Java sample (FizzBuzz instead of JUnit)

- docs/integrate-esm.md
The sample using parcel ([browser-esm-parcel](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-parcel)) does not work due the how parcel handles workers. Added documentation showing how parcel can still be used by bundling workers separately.
> Added documentation for using parcel.

- website/monarch.html
The Monarch tokenizer for JavaScript has a bug where the closing bracket for the RegExp range refers to a `brackets` attribute that does not exist. This bug causes the closing bracket to not be colored using the regexp style.
> Fix JavaScript RegExp range closing bracket

- website/index.html
- website/monarch.html
- website/playground.html
There are some validation errors with the monaco webpages (and others). 
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmicrosoft.github.io%2Fmonaco-editor%2F
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmicrosoft.github.io%2Fmonaco-editor%2Fmonarch.html
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmicrosoft.github.io%2Fmonaco-editor%2Fplayground.html
This PR fixes all the errors apart from the following:
- The link to download the latest version uses the characters '{' and '}' in the href attribute. These aren't valid according to the HTML spec, but I assume these are substituted in by another program.
- A warning for section id playgroud about missing headings
I hope this is useful.
> Fixed various HTML errors with the various webpages

- website/playground/new-samples/interacting-with-the-editor/line-and-inline-decorations/sample.css
'left' style will not work in linesDecorationsClassName, but 'margin-left' do
> Fix lineDecoration example css error

- docs/integrate-esm.md
I just tried this instructions and I found this small detail for they to work perfectly
> fix worker paths in parcel

- test/samples/sample.pascal.txt
- website/index/samples/sample.pascal.txt
This PR adds Pascal source sample to the website.
Its a follow up from https://github.com/Microsoft/monaco-languages/pull/60.
Thank you.
> Add Pascal samples

- test/samples/sample.html.txt
This PR is an HTML sample code to show how to set styles, javascript, add comments, and design a simple page.
> Updated html sample code

- test/samples/sample.aes.txt
Add Sophia ML example.
This is associated with https://github.com/microsoft/monaco-languages/pull/67
> Add Sophia ML example

- website/index/samples/sample.st.txt
As discussed in Microsoft/monaco-languages#66
> Structured text example

- test/playground.generated/extending-language-services-completion-provider-example.html
- website/playground/new-samples/extending-language-services/completion-provider-example/sample.js
Many users are asking about snippet support in Monaco. Enhancing the example on in the playground with a snippet CompletionItem will help users learn about the feature more easily without having to dig through Stack Overflow and GitHub issues.
> Add CompletionItem with snippet support to the example

- website/index/samples/sample.abap.txt
Playground: add ABAP sample
Should fix the error that is currently shown on https://microsoft.github.io/monaco-editor/index.html,
> Playground: add ABAP sample

- website/playground/new-samples/extending-language-services/codelens-provider-example/sample.js
This PR fixes the playground example
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example
it is currently broken with error
guess since https://github.com/microsoft/vscode/commit/35643d80e07f658c705b2b7dfba87b247c834a6b
> Playground: fix codelens provider example

- website/playground/playground.js
<kbd>CTRL/CMD + Enter</kbd> will run the current code in the playground editor.
> Playground: Add keyboard shortcut to run playground code

- .github/workflows/ci.yml
Ensure there is no error when using monaco-editor-core in a ts project
> Validate typings can be imported correctly in simple ts project

- website/monarch.html
Fixes #1805 
I'm not confident I captured the same phrasing & information style as the rest of the docs, and have no emotional attachment to the way it is now if you'd rather re-phrase!
> Added section in Monarch docs for Inspect Tokens development helper

- website/monarch.html
Adds hc-black to the theme options.
Changes wording for #1819.
Adds link to monaco-languages for #1820.
This PR fixes #1819 and fixes #1820.
> Monarch documentation changes

- .github/workflows/ci.yml
- .gitignore
- ci/core.test.ts
- ci/tsconfig.json
- package-lock.json
- package.json
- Migrated and fixed the smoke tests over to Playwright and execute them on webkit/firefox/chromium as discussed with @rebornix
- Adjusted the GitHub Actions, so they run also on a Pull Requests
> feat: fix and migrate smoke tests to Playwright

- ci/core.test.ts
Currently CI is still failing on GitHub Actions.
My guess is that Firefox takes sometimes longer than 2 seconds which is the default timeout, thats why Mocha is failing because it timeouts.
Should be a quick fix for now. Since we only want to check the basic functionality, it should be fine, otherwise I would recommend to e.g. migrate to Jest.
> ci: fixed smoke tests by increasing timeout

- gulpfile.js
TypeScript uses both `'` and `"` in the output, so only one of the contribution changes were being applied - re discussion in #2111
> Adds support for both quotes in the TS side

- monaco.d.ts
- package-lock.json
- package.json
- website/playground/monaco.d.ts.txt
```
Failed to compile.
/my-repo/node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts
TypeScript error in /my-repo/node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts(6235,5):
A 'declare' modifier cannot be used in an already ambient context.  TS1038
6233 |         [index: string]: T;
6234 |     }
> 6235 |     declare type CompilerOptionsValue =
|     ^
6236 |         | string
6237 |         | number
6238 |         | boolean
```
> fix: A 'declare' modifier cannot be used in an already ambient context

- test/playground.generated/extending-language-services-semantic-tokens-provider-example.html
- test/playground.generated/index.html
- website/playground/new-samples/all.js
- website/playground/new-samples/extending-language-services/semantic-tokens-provider-example/sample.html
- website/playground/new-samples/extending-language-services/semantic-tokens-provider-example/sample.js
This is simplified version of [VSCode Semantic tokens sample](https://github.com/microsoft/vscode-extension-samples/tree/master/semantic-tokens-sample) adapted for monaco editor.
> Semantic tokens provider example

- CHANGELOG.md
I'm not sure what release starting 0.21.0 caused it, not other methods being static now beyond parse() and file() in monaco.uri.
Regards and keep doing this amazing project awesomER!
> Missing breaking change

- website/index/samples/sample.csharp.txt
One line used spaces instead of tabs, which meant the code appeared to be incorrectly indented:
> Fixed indentation in C# sample

- website/playground/new-samples/extending-language-services/semantic-tokens-provider-example/sample.js
Fix for "SyntaxError: Invalid regular expression: invalid group specifier name" error displayed in editor, with Safari (version 14 or previous).
Linked to "Lookbehind in JS regular expressions", not supported in Safari: https://caniuse.com/js-regexp-lookbehind
See https://github.com/microsoft/monaco-editor/issues/2459 for details
> Fix error message in Safari - Semantic token play

- test/playground.generated/customizing-the-appearence-exposed-colors.html
- website/playground/new-samples/customizing-the-appearence/exposed-colors/sample.js
According to the pr https://github.com/microsoft/monaco-editor/issues/2507 
I decided to update the color which was missing in the issue. 
`editorActiveLineNumber.foreground` is [deprecated](https://github.com/microsoft/vscode/blob/3718ef05565efeb27e7ee29e50ee77fc82458bb0/src/vs/editor/common/view/editorColorRegistry.ts#L28) so I've added `editorLineNumber.activeForeground` token instead.
> Exposed colors sample update in the playground.

- website/playground/new-samples/customizing-the-appearence/exposed-colors/sample.js
- website/playground/new-samples/extending-language-services/configure-javascript-defaults/sample.js
- website/playground/new-samples/interacting-with-the-editor/adding-an-action-to-an-editor-instance/sample.js
- website/playground/new-samples/interacting-with-the-editor/listening-to-key-events/sample.js
Hi. 
I added 3 small fixes. Two of them are spelling corrections and the other one is an outdated comment
We can't `dispose` `addCommand` anymore... It can create confusion .
> Small update on the website playground

- README.md
Documentation links in the readme file are broken links after the folder was moved
> Fixing the documentation links

- monaco-editor/website/playground/new-samples/extending-language-services/semantic-tokens-provider-example/sample.js
- [Semantic Tokens Provider Sample Playground Link](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example)
https://user-images.githubusercontent.com/29809906/141407743-72cdc5d5-32f3-4473-8220-df6d55c3b996.mov
- Issue occurred due to the missing colors key in the defineTheme API's ThemeDataObject
- The colors key seems to be **required** as it is not mentioned as optional in the [Interface IStandaloneThemeData](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneThemeData.html)
- Adding colors key in the ThemeDataObject fixes the issue
> Semantic Tokens Provider Sample is broken in docs

- src/typescript/tsWorker.ts
- test/smoke/runner.js
- test/smoke/smoke.test.js
I've migrated our infra over to handle the new monorepo, but hit a blocker. In the older versions of monaco-typescript, importing `vs/language/typescript/tsWorker` would trigger `window.ts` to become the TypeScript object. 
This is _generally_ considered a  feature (of a side effect) when importing typescriptServices.js because of this `var`:
I used that to access the same version of TypeScript as the monaco webworker in the Playground. 
I'm not tied to the implementation detail as it's easy to do both, so I felt this might be more ESM-y instead of jamming a `window.ts = ts` at the end but I think it depends on whether this is classed as a breaking change (and I guess if other people used that side-effect) in which case this can be switched out
> Expose the TypeScript object inside the ts worker

- monaco-editor/website/playground/new-samples/interacting-with-the-editor/adding-an-action-to-an-editor-instance/sample.js
Documentation for [`editor.AddAction`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IActionDescriptor.html#run) gives a return type of `void | Promise<void>`. Having the example `return null` is confusing given it doesn't really matter what it returns.
> Remove return from example addAction

- build/importTypescript.js
- src/typescript/tsWorker.ts
- test/smoke/smoke.test.js
It looks like the prior PR https://github.com/microsoft/monaco-editor/pull/2770 was close, but not quite. The object available is the exported set of vars at the end of `typescriptServices.js`: 
Which isn't the typescript API, just a subset (used for ESM support I assume) - this means you don't get access to the underlaying `ts`.  To work around this, I've done a bit of a dance of exporting `typescript` from this object and then later adding that to the `globalThis`.
To validate, I've added to the smoketest for a non-exported property from the TypeScript compiler API. Nice test suite BTW 👍🏻 
---
I took a look at what changed in the JS between:
- monorepo: https://typescript.azureedge.net/cdn/4.6.0-dev.20211115/monaco/dev/vs/language/typescript/tsWorker.js
- before: …
> Expose full ts object to global ts

- src/basic-languages/protobuf/protobuf.ts
see this issue. https://github.com/microsoft/monaco-editor/issues/2700 Just simply `switchTo` proto2 token if there is no `sytanx=` provided.
> Fix token while missing `syntax=` directive

- src/basic-languages/markdown/markdown.test.ts
- src/basic-languages/markdown/markdown.ts
> Support hyphenated HTML tags in Markdown syntax

- src/basic-languages/freemarker2/freemarker2-angle-bracket.test.ts
- src/basic-languages/freemarker2/freemarker2-angle-dollar.test.ts
- src/basic-languages/freemarker2/freemarker2-auto-bracket.test.ts
- src/basic-languages/freemarker2/freemarker2-auto-dollar.test.ts
- src/basic-languages/freemarker2/freemarker2-bracket-bracket.test.ts
- src/basic-languages/freemarker2/freemarker2-bracket-dollar.test.ts
- src/basic-languages/freemarker2/freemarker2.contribution.ts
- src/basic-languages/freemarker2/freemarker2.ts
- src/basic-languages/monaco.contribution.ts
- website/index/samples/sample.freemarker2.tag-angle.interpolation-bracket.txt
- website/index/samples/sample.freemarker2.tag-angle.interpolation-dollar.txt
- website/index/samples/sample.freemarker2.tag-auto.interpolation-bracket.txt
- website/index/samples/sample.freemarker2.tag-auto.interpolation-dollar.txt
- website/index/samples/sample.freemarker2.tag-bracket.interpolation-bracket.txt
- website/index/samples/sample.freemarker2.tag-bracket.interpolation-dollar.txt
- website/index/samples/sample.freemarker2.txt
Woah, test cases got really large, much larger than the implementation...
Adds syntax highlighting support for [Apache FreeMarker](https://freemarker.apache.org/), resolves #2383. Includes tests and samples for the website.
* Language ID is `freemarker2` since [FreeMarker 3 will most likely change the syntax](https://cwiki.apache.org/confluence/display/FREEMARKER/FreeMarker+3)
* FreeMarker actually defines 6 slightly different syntaxes. Therefore this commit adds the 6 language modes `freemarker2.tag-*.interpolation-*`. It also adds the mode `freemarker2`, which is an alias for `freemarker2.tag-angle.interpolation-dollar`, the default mode when using FreeMarker via the Java API.
* If anybody has a better suggestion for naming the modes, feel free to suggest it. 
---
(from the source code …
> Implements #2383 Add syntax modes for FreeMarker template language

- src/basic-languages/shell/shell.test.ts
- src/basic-languages/shell/shell.ts
This PR fix #2851. The fix is correcting the regex that highlight the attributes and create a new regex for identifiers containing dashes.
This impact the Monaco editor playground only.
You can test by running the tests:
>npm run release
>npm run test
Two new tests added, one for the bug reported and one for the new regex defined (identifiers with dashes).
> Fix #2851 Highlight correctly the attributes and identifiers (with dashes) for Shell language

- src/basic-languages/swift/swift.ts
Citing [this pull request](https://github.com/apple/swift/pull/41022), the Core Swift team has decided on adding the new keyword to Swift 5.6. This will also ensure that syntax coloring for Swift-Colab is as up-to-date as possible if Google suddenly ups their monaco dependency from 0.27 to current.
> Add @preconcurrency to Swift declaration attributes

- .github/workflows/publish.yml
Currently, the publish workflow will automatically run in any fork of the main repo, triggering an action failure once a week.
This PR adjusts the workflow so that it'll check if it's running in the main repo before attempting to run the job, so it'll continue to work the same in the main repo, and just not run at all in forks.
This could also be applied to the other workflows that run on cron jobs if desired.
> Only run publish workflow on main monaco-editor repo

- .gitattributes
See [here](https://hediet.github.io/git-line-endings/?os=windows&eol=undefined&core_eol=lf&core_autocrlf=false&text=auto) for the effect of this setting.
That way, new files (and existing files without crlf) are always committed as lf, regardless of any local settings.
> Adds .gitattributes to ensure all source files are stored as LF in git.

- src/basic-languages/javascript/javascript.contribution.ts
This extension is used by node projects of `"type": "module"` for files that are still written using CommonJS (for example configuration files).
> Add .cjs extension for javascript files

- src/basic-languages/swift/swift.ts
This is part of the AutoDiff modifiers, alongside `@derivative` and `@differentiable`. I forgot to add it in a previous commit. It's used extensively in differentiable Swift, for example [here](https://github.com/tensorflow/swift-apis/blob/f51ee4618d652a2419e998bf9418ad80bda67454/Sources/TensorFlow/Layers/Dropout.swift#L40).
> Add `@noDerivative` modifier to Swift

- docs/integrate-esm.md
The current sample code for "Using Vite" works fine in Chrome, but causes errors in Firefox: 
`Error: import declarations may only appear at top level of a module`
In addition to many errors logged to the console, this also causes subtle bugs in Firefox (e.g. the highlighting in the diff editor didn't work).
The problem appears to be that Firefox requires an explicit `type: module` for the web workers.
The revised implementation for Vite takes this into account and has been tested successfully in Chrome and Firefox.
> Make Vite sample code Firefox compatible

- package-lock.json
- package.json
monaco-typescript builds of TypeScript 4.6 and nightlies are failing due to a TS API change that ts-node needed to account for: https://github.com/microsoft/TypeScript/issues/47921 / https://github.com/TypeStrong/ts-node/pull/1648. The ts-node fix was just published to v10.6. We need this in order to get new versions of TypeScript up on the playground. Thanks!
> Upgrade ts-node

- src/language/typescript/tsWorker.ts
The comment from @weswigham on these methods says
```
/*
* Unlike `realpath and `readDirectory`, `readFile` and `fileExists` are now _required_
* to properly acquire and setup source files under module: node12+ modes.
*/
```
Obviously monaco-editor can’t read files, so I assume this is the closest we’re going to get. I’m not sure when/if these methods will get called, but the Playground does let you select node12/nodenext module settings, so I think throwing a not-implemented error would likely show up. @weswigham can you review please?
> Add new required methods to LanguageServiceHost

- src/basic-languages/yaml/yaml.ts
If a line ends with `:` and a user presses Enter, they are probably defining an object, which requires indentation.
[This rule is taken from `monaco-yaml`](https://github.com/remcohaszing/monaco-yaml/blob/main/src/yamlMode.ts#L41-L45), but I intend to remove basic language support there, since that’s already part of `monaco-editor`.
> Add yaml indent action

- src/basic-languages/typescript/typescript.ts
see https://github.com/microsoft/TypeScript-Website/issues/2329 and https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/#optional-variance-annotations-for-type-parameters
> add `out` keyword to typescript

- src/basic-languages/css/css.ts
- src/basic-languages/less/less.ts
- src/basic-languages/scss/scss.ts
Adds the fr units to all of the styling syntax highlighting. The `fr` units represents fractions of the avaliable space and is used in the CSS Grid.
> feat: add fr units for css grid

- webpack-plugin/README.md
I had to do a lot of digging in the source code just to know what strings I can use in the features list. Adding this allows users to find out for themselves. I considered adding the list here but I don't know if it might change depending on your build.
> [webpack readme] Add how to get languages/features

- src/basic-languages/mysql/mysql.test.ts
PR removes three duplicate tests from the mysql language. They are a copy of the three tests immediately above.
> Remove duplicate testcases for mysql

- src/basic-languages/cypher/cypher.contribution.ts
- src/basic-languages/cypher/cypher.test.ts
- src/basic-languages/cypher/cypher.ts
- src/basic-languages/monaco.contribution.ts
Language configuration and a tokenizer are created from the following Cypher (`openCypher`) resources:
* Cypher Query Language Reference (Version 9): https://opencypher.org/resources/
From `CONTRIBUTING.md`:
> Please understand that we only bundle languages with the Monaco editor that have a significant relevance (for example, those that have an article in Wikipedia).
Here is the wiki: https://en.wikipedia.org/wiki/Cypher_(query_language)
Cypher is a declarative graph query language for graph databases. Cypher was largely an invention of Andrés Taylor while working for Neo4j, Inc. (formerly Neo Technology) in 2011. Cypher was originally intended to be used with the graph database Neo4j, but was opened up through the `openCypher` project in October 2015.
Cypher is being used and …
> Add config and tokenizer for query language Cypher

- docs/integrate-esm.md
There is a missing in `integrate-esm.md`, make the link be not working.
> Fix menu link in integrate-esm.md

- website/typedoc/monaco.d.ts
> [DOCS] IEditorOptions.automaticLayout uses ResizeObserver 3051

- src/language/typescript/tsWorker.ts
fix issue #2295
component: `TypeScriptWorker` (`tsWorker.ts`)
- Enable '**skipEncoding**' flag on `Uri.toString` invokation on `getScriptFileNames()` method
- Compare '**fileName**' argument provided to `_getModel()` method both with Uri encoded and not
> Fix issue #2295 - Models with "@" in their name do not resolve as dependencies

- build/importTypescript.ts
- src/language/typescript/lib/typescriptServices.d.ts
Incremental step towards removing `typescriptServices.js` from the typescript package. See https://github.com/microsoft/TypeScript/issues/50758.
> Use typescript.js as source for typescriptServices

- website/playground/new-samples/extending-language-services/color-provider-example/sample.js
Fix the example so that the document colors' ranges encompass the entire word.
Fixes https://github.com/microsoft/monaco-editor/issues/3347
> Fix the color provider's columns

- .prettierignore
This adds `/test/smoke/vite/dist` and `/test/smoke/parcel/dist` in `.prettierignore` -- whenever you build the project locally, these directories add unnecessary length to local formatting and don't need to be formatted as they are already ignored.
> Ignore dist from vite/parcel in prettier

- src/basic-languages/xml/xml.contribution.ts
Directory.Build.props and Directory.Build.targets are commonly used in C# solutions.  (See https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022.)  These have the usual MSBuild syntax, which is just XML (c.f. `.csproj`).
Note - if the PR needs to be updated to be `.Build.props` and `.Build.targets` that's fine.
> Add .props & .targets as XML extensions

- src/language/typescript/monaco.contribution.ts
- src/language/typescript/tsMode.ts
This commit implements the functionality requested in #3155.
The work is done based on the implementation for the the css, html and json namespaces.
In this case the `ModeConfiguration` interface implementation has the following options:
```typescript
export interface ModeConfiguration {
/**
* Defines whether the built-in completionItemProvider is enabled.
*/
readonly completionItems?: boolean;
/**
* Defines whether the built-in hoverProvider is enabled.
*/
readonly hovers?: boolean;
/**
* Defines whether the built-in documentSymbolProvider is enabled.
*/
readonly documentSymbols?: boolean;
/**
* Defines whether the built-in definitions provider is enabled.
*/
readonly definitions?: boolean;
/**
* Defines whether the built-in references provider is enabled.
*/
readonly references?: …
```
> Add setModeConfiguration for monaco.languages.typescript.[typescript|javascript]Defaults

- samples/browser-esm-webpack-small/index.js
The `npm run build` step for the `browser-esm-webpack-small` example is currently failing due to an outdated import path referencing `findController` in its `index.js`.
I've fixed the build by updating the import path to `findController`'s [current location](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/find/browser/findController.ts).
> Update import path for `browser-esm-webpack-small`

- src/language/typescript/languageFeatures.ts
> Fixes bug that entries would be marked as deprecated if kindModifiers is undefined.

- website/src/website/data/playground-samples/extending-language-services/model-markers-example/sample.js
When I was learning Monaco Editor from the playground, I saw that the sample 'model-markers-example' did not work.
Before:
After:
> Fix the sample 'model-markers-example' compilation failure

- website/src/website/data/playground-samples/extending-language-services/hover-provider-example/sample.js
when I visit monaco editor website， I find [this example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-extending-language-services-hover-provider-example) is error。 can't get playground.html, and 404。
Then I git clone monaco editor and run dev。 finally I find that after website restructure， the file `playground.html`  at root directory。
> fix: fix hover example

- website/src/website/data/playground-samples/extending-language-services/hover-provider-example/sample.js
The example [Hover Provider Example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-extending-language-services-hover-provider-example) has incorrect Promise syntax, It doesn't affect the operation, but I still fixed it.
> Fix 'Hover Provider Example' incorrect Promise syntax

- website/src/website/data/playground-samples/creating-the-editor/hard-wrapping/sample.js
example 
https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-creating-the-editor-hard-wrapping
opt example, remove new version not support attr `wordWrapMinified` on create editor。
> opt example 

- src/language/typescript/languageFeatures.ts
- src/language/typescript/monaco.contribution.ts
- src/language/typescript/tsMode.ts
- src/language/typescript/tsWorker.ts
We just removed this in https://github.com/microsoft/TypeScript/pull/52347 but now we can't build the playground (oops).
Somehow we didn't find this use. We have had document highlights for a good while, so we can use it here.
> Replace occurrences with highlights

- build/releaseMetadata.ts
According to the examples, this is part of the public interface. However, type definitions were missing for these files.
Closes #2450
> Publish feature and language type definitions

- .github/workflows/ci.yml
- website/package.json
- website/scripts/check-playground-samples-js.ts
- website/src/website/data/playground-samples/creating-the-editor/syntax-highlighting-for-html-elements/sample.js
- website/src/website/data/playground-samples/customizing-the-appearence/exposed-colors/sample.js
- website/src/website/data/playground-samples/extending-language-services/configure-javascript-defaults/sample.js
- website/src/website/data/playground-samples/extending-language-services/custom-languages/sample.js
- website/src/website/data/playground-samples/extending-language-services/inlay-hints-provider-example/sample.js
- website/src/website/data/playground-samples/interacting-with-the-editor/adding-a-command-to-an-editor-instance/sample.js
- website/src/website/data/playground-samples/interacting-with-the-editor/listening-to-mouse-events/sample.js
- website/yarn.lock
I found several playground samples have type errors.
So I added type checking test script and test CI to github actions.
> Fix playground samples type errors and add CI test

- website/package.json
- website/tsconfig.json
- website/yarn.lock
https://github.com/microsoft/monaco-editor/pull/3855 was due to `require()` breaking change in TS 4.9.
But we don't need to transpile dynamic import to `require()`, so I change moduleResolution to `node16` and reverted merge commit.
> Change moduleResolution to node16 and adopt TS 5.0

- src/basic-languages/xml/xml.contribution.ts
Fixes #3865.
Not sure what the policy on extensions is. There is `.csproj` but not `.vbproj` or any other `.*proj`. Other reasonable candidates might be `.*manifest` and `.*config`.
> Include .xsd and .xslt as an XML extension

- src/language/typescript/languageFeatures.ts
As the result object is about to be created, it can not be referred to when mapping child items.
This fixes #3923
> Fix reference error in convert method of OutlineAdapter

- webpack-plugin/src/loaders/include.ts
I replaced the CJS `require` and `module.exports` with `import` and `export` statements. 
This PR should fix #2735.
Tests are ok on my dev environment.
> [Webpack Plugin] Fix CJS being injected in ESM files

- src/basic-languages/javascript/javascript.ts
JS supports the static keyword as of ES2022, this PR adds it to the list of keywords.
> [JS] Add static keyword

- src/basic-languages/javascript/javascript.test.ts
- src/basic-languages/typescript/typescript.test.ts
- src/basic-languages/typescript/typescript.ts
Fixes #3254 
This is a very simple solution that just allows the `#` character as the start character of identifiers for all identifiers. I don't know Monarch enough to know if there is a way to constrain this to identifiers in classes, but I doubt there is. In any case if you use the `#` character at the start of e.g. a variable name the language service raises an error diagnostic, so that this might not be a problem? Maybe this simple solution is enough for this issue. Let me know what you think, or feel free to discard this.
**Local Playground Link**: https://microsoft.github.io/monaco-editor/playground.html?sourceLanguages=http%3A%2F%2Flocalhost%3A5002%2Fout%2Flanguages%2Famd-tsc#XQAAAAJoAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzblk-_1 …
> [JS, TS] Add Monarch support for private identifiers

- website/src/website/data/playground-samples/interacting-with-the-editor/rendering-glyphs-in-the-margin/sample.css
Following up on https://github.com/microsoft/monaco-editor/issues/3929. It might be helpful to include recommended solution in the example. Otherwise demo example looks broken as selection is not working as expected.
After
https://user-images.githubusercontent.com/963490/236619213-78b24ed2-8b7c-4aea-96d6-0b858975f653.mov
Before
https://user-images.githubusercontent.com/963490/233871151-11bd5f67-4726-414f-9629-9c154a001c05.mov
> Extend the "Rendering Glyphs In The Margin" example to include a transparent color note.

- website/src/website/pages/home/Home.tsx
The github.io page for this has lorem ipsum text in a prominent position on the page. This replaces it with real text.
> Fix lorem ipsum text on marketing page.

- src/basic-languages/elixir/elixir.test.ts
- src/basic-languages/elixir/elixir.ts
Elixir v1.15.0 has added support for multi-letter uppercase sigils, eg:
```elixir
~LVN/content/
~LVN/content/m
```
Previously only a single letter was supported so these changes keep backwards compatibility.
Proposal: https://groups.google.com/g/elixir-lang-core/c/cocMcghahs4/m/DdYRNfuYAwAJ
PR: https://github.com/elixir-lang/elixir/pull/12448
Release notes: https://github.com/elixir-lang/elixir/releases/tag/v1.15.0
> Elixir - Add support for multi-letter uppercase sigils

- .github/workflows/website.yml
The new one allows you to specify GITHUB_TOKEN permissions in the workflows file... which means forkers don't need to dig through GUI settings to get it working. It also doesn't require a second noisy branch to function, and can help reduce package size for large repos. An 800MB repo doesn't sound like a lot, but thats before Yarn and Playwright have a go at your poor computer, also my 16GB computer has been screaming at me about RAM usage, not sure if that had something to do with it.
P.S. I was working on something far more exciting... this is just to test the waters.
Also, I was surprised to see so many samples, good ones, that aren't exposed on the website.
proof that it works:
https://github.com/FossPrime/monaco-editor/actions/runs/5166983110
> Use new GitHub pages workflow

- README.md
I think this captures the basics. I’m open to suggestions.
IMO this is brief enough to keep in the readme, but I can move it into `/docs/basic-concepts` or so and link that if that’s preferable.
Closes #4084
> Document some basic concepts

- src/language/json/jsonWorker.ts
fixes #4209 
Implemented according to [this suggestion](https://github.com/microsoft/vscode-json-languageservice/commit/2f4f0aa4b6ce2b3b77d821466740a43bbdf96127#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) from `vscode-json-languageservice`
> fix: enable markdown in JSON completion details

- src/basic-languages/cpp/cpp.ts
In the cpp tokenizer, angled brackets (`<>`) were separated from other brackets to hold an additional post-condition:
```js
...
[/[{}()\[\]]/, '@brackets'],
[/[<>](?!@symbols)/, '@brackets'],    // <----
```
Not sure why, one guessed motivation is that a tokenizer needs to be extra careful with `<` since it might eventually resolve to the operator `<<`. However, 
(1) this doesn't solve it, `<<` is still not tokenized to an operator (it fails all tokenizer regexes), 
(2) this extra-liberal exclusion causes bugs like #4253.
This suggested fix treats angled-brackets identically to other brackets. A true c++-conforming tokenizer might require `@rematch` and other heavy machinery, but this one is pretty certain to be at least some step forward.
> Fix suggestion for #4253

- src/basic-languages/cpp/cpp.ts
cpp has no `>>>`, I'm guessing it's a leftover from somewhere else.
> Remove 2 java-only operators from c++ tokenizer

- README.md
Currently the link to the monaco.d.ts on the github.io domain serves the file as a MP4.
Coming in from a non-contributor perspective, it is difficult to find the monaco.d.ts file within the repository, hence this PR.
> chore(docs): fix monaco.d.ts link

- src/language/json/jsonMode.ts
- src/language/json/jsonWorker.ts
- src/language/json/monaco.contribution.ts
This PR fixes microsoft#727 and addresses review comments (I think so) from an original PR microsoft#3956 which became stale for some reason.
I just want to get things JSON worker faster to Monaco, because it's needed for my project.
My use case is to provide insights to the end user after analyzing JSON schemas of the edited document. Plus, include the motivation from an original PR: 
> Exposes the JSON worker and the parseDocument function from the JSON Worker.
>
> This is useful when editors want to use the JSON Worker's ability to parse the document, as using a separate parser can result in inconsistencies and does double the work.
> Expose JSON worker

- .azure-pipelines/publish-nightly.yml
- .azure-pipelines/publish-stable.yml
This pull request fixes the parameter labels in the `.azure-pipelines/publish-nightly.yml` and `.azure-pipelines/publish-stable.yml` files. The display name for publishing the Monaco Editor Core has been corrected to "🚀 Publish Monaco Editor".
> Fix parameter labels

- .azure-pipelines/publish-nightly.yml
- .azure-pipelines/publish-stable.yml
Some of the builds require Linux, so we skip APIScan for those builds.
Will investigate why the nightly build's broken separately.
> chore: skip APIScan

- .azure-pipelines/publish-stable.yml
Ignores the dependencies/vscode/extensions folder because
1. The VS Code extensions are scanned elsewhere
2. The VS Code extension package.json files often produce false positives because they share names with published npm packages such as grunt and ini
> chore: add cgIgnoreDirectories

- package-lock.json
- package.json
- src/basic-languages/cpp/cpp.ts
Since https://github.com/microsoft/vscode/pull/183463 was merged it should now be possible to fix #3128 with this.
In order to test it I need to be able to be able to run the monaco-editor locally with this new change from upstream. What can I do to get that change locally?
> Fix bug with highlighting of C++ raw string literals

- .azure-pipelines/publish-nightly.yml
Some VS Code CG scan results are being re-reported by the monaco-editor (nightly) CG scan. This PR ignores the dependencies/vscode/extensions folder to close some duplicate CG results.
@hediet is it possible for the monaco-editor pipeline to pull in an outdated version of VS Code? If not, I believe we can ignore the entire dependencies/vscode folder in a future PR.
> chore: CG ignore VS Code extensions for nightly

- .azure-pipelines/publish-nightly.yml
- .azure-pipelines/publish-stable.yml
This PR excludes all vscode folders from CG. I have confirmed that the scanned results already show up in a separate CG scan.
> chore: exclude all vscode from CG

- src/basic-languages/csp/csp.contribution.ts
Adds the missing extension value for the CSP langugage in `csp.contribution.ts`.
**Fixes: #4503**
---
_xref: microsoft/PowerToys/issues/32771_
> Add extension to `csp.contribution.ts`

- samples/browser-script-editor/index.html
- website/src/website/monaco-loader-chunk.ts
- website/static/monarch-static.html
> Removing `editor.main.nls.js`
